---
# tasks file for k8s-cluster
#
#Including task according to os family

- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

# Setup Master Node

- name: Configuring master node
  import_tasks: master-node.yml
  when: kubernetes_node == "MasterNode"
  
# Creating token to attach slave node to master node

- command: "kubeadm token create  --print-join-command"
  register: WorkerNodeToken
  when: kubernetes_node == "MasterNode"


# Setting the kubeadm join command globally

- set_fact: 
    node_join_cmd: "{{ WorkerNodeToken.stdout }}"
  when: WorkerNodeToken.stdout is defined and kubernetes_node == "MasterNode"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"


# Configuring Kubernetes slave node

- include_tasks: slave-node.yml
  when: kubernetes_node == "SlaveNode"

